Repository ChessAdventure/client, pull requests merged in 2021-04, with the labels that each got.

#1 Setup
  package-lock.json
  package.json
Labels: FE

#7 Feature/component structure
  src/App.tsx
  src/components/App/App.css
  src/components/App/App.test.js
  src/components/App/App.tsx
  src/components/Dashboard/Dashboard.tsx
  src/components/EndGame/EndGame.tsx
  src/components/GameBoard/GameBoard.tsx
  src/components/GameScreen/GameScreen.tsx
  src/components/Header/Header.tsx
  src/components/OldGameBoard/OldGameBoard.tsx
  src/components/PastGames/PastGames.tsx
  src/components/PlayerThumbnail/PlayerThumbnail.tsx
  src/components/QuestStart/QuestStart.tsx
  src/components/Splash/Splash.tsx
  src/components/UserProfile/UserProfile.tsx
  src/components/UserProfileImage/UserProfileImage.tsx
  src/components/UserProfilePage/UserProfilePage.tsx
  src/index.tsx
Labels: FE

#27 Feature/responsive login
  public/favicon.ico
  public/index.html
  src/components/SignUp/SignUp.css
  src/components/SignUp/SignUp.tsx
  src/components/Splash/Splash.css
  src/components/Splash/Splash.tsx
  src/index.css
  src/splash-background.jpg
Labels: FE, enhancement

#29 Cypress
  .github/workflows/cypress.yml
  cypress.json
  cypress/fixtures/login.json
  cypress/fixtures/start-game.json
  cypress/integration/dashboard.spec.js
  cypress/integration/login.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/components/Dashboard/Dashboard.css
  src/components/Dashboard/Dashboard.tsx
  src/components/GameScreen/GameScreen.tsx
  src/components/Header/Header.css
  src/components/Header/Header.tsx
  src/components/OldGameBoard/OldGameBoard.tsx
  src/components/QuestStart/QuestStart.css
  src/components/QuestStart/QuestStart.tsx
  src/components/UIComponents/Gameboard/Gameboard.tsx
  src/components/UIComponents/Thumbnail/Thumbnail.css
  src/index.tsx
Labels: FE, Testing

#40 Center gameboard
  src/components/SignUp/SignUp.tsx
  src/components/UIComponents/Gameboard/Gameboard.tsx
Labels: FE, bug

#45 Feature/cypress dashboard
  cypress/integration/dashboard.spec.js
  src/components/App/App.css
  src/components/App/App.tsx
  src/components/Dashboard/Dashboard.css
  src/components/Dashboard/Dashboard.tsx
  src/components/GameOver/GameOver.css
  src/components/GameOver/GameOver.tsx
  src/components/GameScreen/GameScreen.css
  src/components/GameScreen/GameScreen.tsx
  src/components/OldGameBoard/OldGameBoard.tsx
  src/components/QuestStart/QuestStart.tsx
  src/components/Rules/Rules.tsx
  src/components/SignUp/SignUp.css
  src/components/SignUp/SignUp.tsx
  src/components/UIComponents/Gameboard/Gameboard.css
  src/components/UIComponents/Gameboard/Gameboard.tsx
  src/constants/index.js
Labels: FE, Testing

#46 Add winning streak to dashboard
  cypress/integration/dashboard.spec.js
  src/components/Dashboard/Dashboard.tsx
Labels: FE, enhancement
